[kotlin] Use impl class references for PsiNameHelper dependency injection
It's necessary because, when updating IJ SDK (KT-80525) in the compiler,
we start injecting this component for tests and the j.l.Class overload
allows re-registering the component, while the one that accepts
an instance throws an exception like:

com.intellij.util.pico.PicoException: Key com.intellij.psi.PsiNameHelper duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:105)
    at com.intellij.util.pico.DefaultPicoContainer.registerComponentInstance(DefaultPicoContainer.java:159)
    at com.intellij.mock.MockComponentManager.registerService(MockComponentManager.java:129)
    at org.jetbrains.uast.test.kotlin.AbstractKotlinUastTest.initializeCoreEnvironment(AbstractKotlinUastTest.kt:153)
    at org.jetbrains.uast.test.kotlin.AbstractKotlinUastTest.getVirtualFile(AbstractKotlinUastTest.kt:115)
    at org.jetbrains.uast.test.kotlin.AbstractKotlinUastTest.doTest(AbstractKotlinUastTest.kt:92)
    at org.jetbrains.uast.test.kotlin.AbstractKotlinUastTest.doTest$default(AbstractKotlinUastTest.kt:88)

GitOrigin-RevId: 73a01c9029f874555d0bb8593600deb5a07dd502