[kotlin][fe10 bindings] KtSymbolBasedValueParameterDescriptor: fix flaky result
FIR declarations can have several KtValueParameterSymbol
KtSymbol can be recreated due to GC

```stacktrace
java.lang.IllegalStateException: Parameter not found in container symbol = org.jetbrains.kotlin.analysis.api.fir.symbols.KtFirFunctionSymbol@72679a11
  at org.jetbrains.kotlin.idea.fir.fe10.KtSymbolBasedValueParameterDescriptor.<init>(BaseDescriptorsWrappers.kt:531)
  at org.jetbrains.kotlin.idea.fir.fe10.KtSymbolBasedValueParameterDescriptor.<init>(BaseDescriptorsWrappers.kt:515)
  at org.jetbrains.kotlin.idea.fir.fe10.Fe10WrapperContextKt.toDeclarationDescriptor(Fe10WrapperContext.kt:99)
  at org.jetbrains.kotlin.idea.fir.fe10.Fe10WrapperContextKt.toDeclarationDescriptor(Fe10WrapperContext.kt:105)
  at org.jetbrains.kotlin.idea.fir.fe10.Fe10WrapperContextKt.toDeclarationDescriptor(Fe10WrapperContext.kt:62)
  at org.jetbrains.kotlin.idea.fir.fe10.binding.CallAndResolverCallWrappers.getReferenceTarget(CallAndResolverCallWrappers.kt:170)
  at org.jetbrains.kotlin.idea.fir.fe10.binding.CallAndResolverCallWrappers.access$getReferenceTarget(CallAndResolverCallWrappers.kt:26)
  at org.jetbrains.kotlin.idea.fir.fe10.binding.CallAndResolverCallWrappers$4.invoke(CallAndResolverCallWrappers.kt:33)
  at org.jetbrains.kotlin.idea.fir.fe10.binding.CallAndResolverCallWrappers$4.invoke(CallAndResolverCallWrappers.kt:33)
  at org.jetbrains.kotlin.idea.fir.fe10.binding.KtSymbolBasedBindingContext.get(KtSymbolBasedBindingContext.kt:48)
  ```

GitOrigin-RevId: a0bbc5515a42f45b09aa5157c7111cb12eb2625e