ExternalSystemUtil: more verbose error reporting
Right now, I'm investigating
`ProjectTemplateNewWizardProjectImportTestGenerated.GradleKts.testComposeMultiplatformApplication`
test failures.

And stracktraces from TeamCity look like this:

  junit.framework.AssertionFailedError: ProjectImportingError(kotlinVersion=1.6.10, reason=begin 0, end 234, length 130)
    at junit.framework.Assert.fail(Assert.java:57)
    at junit.framework.TestCase.fail(TestCase.java:227)
    at org.jetbrains.kotlin.tools.projectWizard.cli.TestUtilsKt.assertSuccess(testUtils.kt:113)
    at org.jetbrains.kotlin.tools.projectWizard.wizard.AbstractNewWizardProjectImportTest.runWizard(AbstractNewWizardProjectImportTest.kt:120)
    at org.jetbrains.kotlin.tools.projectWizard.wizard.AbstractNewWizardProjectImportTest.doTest(AbstractNewWizardProjectImportTest.kt:106)

"begin 0, end 234, length 130" part is completely not obvious. Now we
will include "caused by" exception at least

GitOrigin-RevId: 87c6bee7c8bd48b93ddb2f51757a908bba5645c3