KotlinBundledPathMacroContributor: make check for file existence atomic
This commit fixes this exception:

  2023-07-06 13:18:34,934 [ 136393] SEVERE - #c.i.o.p.u.BackgroundTaskUtil - java.nio.file.NoSuchFileException: /opt/teamcity-agent/temp/buildTmp/startupPerformanceTests17370028913378750440/perf-startup/cache/projects/unpacked/Anki-Android/.idea/kotlinc.xml
  java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: /opt/teamcity-agent/temp/buildTmp/startupPerformanceTests17370028913378750440/perf-startup/cache/projects/unpacked/Anki-Android/.idea/kotlinc.xml
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.tryAwaitFuture(BackgroundTaskUtil.java:313)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$9(BackgroundTaskUtil.java:292)
    at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
    at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
    at com.intellij.openapi.util.Disposer.dispose(Disposer.java:262)
    at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$12(BackgroundTaskUtil.java:305)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
    at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
    at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.nio.file.NoSuchFileException: /opt/teamcity-agent/temp/buildTmp/startupPerformanceTests17370028913378750440/perf-startup/cache/projects/unpacked/Anki-Android/.idea/kotlinc.xml
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
    at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
    at java.base/java.nio.file.Files.getLastModifiedTime(Files.java:2402)
    at com.intellij.util.io.PathKt.lastModified(path.kt:103)
    at org.jetbrains.kotlin.idea.macros.KotlinBundledPathMacroContributor.getProjectPathMacros(KotlinBundledPathMacroContributor.kt:39)
    at com.intellij.openapi.components.impl.ProjectWidePathMacroContributor.getAllMacros(ProjectWidePathMacroContributor.java:41)
    at com.intellij.openapi.components.impl.ProjectPathMacroManager.getExpandMacroMap(ProjectPathMacroManager.java:49)
    at com.intellij.openapi.components.PathMacroManager.expandPath(PathMacroManager.java:116)
    at com.intellij.openapi.externalSystem.service.project.autoimport.ProjectAware.getSettingsFiles(ProjectAware.kt:40)
    at com.intellij.openapi.externalSystem.autoimport.ProjectSettingsTracker$SettingsFilesAsyncSupplier$cachingAsyncSupplier$1.get(ProjectSettingsTracker.kt:345)
    at kotlin.jvm.internal.PropertyReference0.invoke(PropertyReference0.java:35)
    at com.intellij.openapi.externalSystem.autoimport.settings.AsyncSupplier$Companion$blocking$1.supply(AsyncSupplier.kt:19)
    at com.intellij.openapi.externalSystem.autoimport.settings.BackgroundAsyncSupplier.supply$lambda$0(BackgroundAsyncSupplier.kt:18)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$submitTask$8(BackgroundTaskUtil.java:266)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$10(BackgroundTaskUtil.java:302)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$11(BackgroundTaskUtil.java:297)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    ... 13 more

The exception is reported in the comments of KTIJ-23700

GitOrigin-RevId: 07a971982adb019080ceb94ffd3b476c45789eb5