Fix GradleKtsImportTest
To be precise this commit fixes 3 tests:
GradleKtsImportTest.testCompositeBuild[0: with Gradle-6.0.1]
GradleKtsImportTest.testEmpty[0: with Gradle-6.0.1]
GradleKtsImportTest.testError[0: with Gradle-6.0.1]

Those tests were broken by 29035f902dfd713b86ec76e55dd4adc52ad51aa1 in intellij

Stacktrace:
```
junit.framework.AssertionFailedError: Import failed: 'void net.rubygrapefruit.platform.internal.NativeLibraryLocator.<init>(java.io.File, java.lang.String)'
java.lang.NoSuchMethodError: 'void net.rubygrapefruit.platform.internal.NativeLibraryLocator.<init>(java.io.File, java.lang.String)'
	at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:34)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:120)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:84)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.mergeJvmArgs(GradleExecutionHelper.java:385)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.prepare(GradleExecutionHelper.java:278)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.prepare(GradleExecutionHelper.java:254)
	...
```

Test failure happens because Kotlin compiler and IJ platform use different versions of 'gradle-api'.
By setting explicit dependency on 'Gradle' library I enforce to use 'gradle-api' from IJ not the compiler

GitOrigin-RevId: b16bfd38bb35a5965dd4663810180936c4c09355