Kotlin debugger tests: use ProcessBuilder instaed of javac API
In scope of: KTIJ-24003 & KTIJ-24039
Review: https://jetbrains.team/p/ij/reviews/100488

This commit fixes a bunch of debugger tests that fail locally but pass
on CI (the failures are reproducible on my machine and on machine of Yan
Zhulanow)

Test example: `org.jetbrains.kotlin.idea.debugger.test.KotlinSteppingTestGenerated.StepInto#testJavaSamFunction`
It was failing locally with:
```
java.lang.UnsupportedClassVersionError: forTests/MyJavaClass has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

I think that using javac API in this place is weird. "process" is much
more widely known concept that everyone understands and that is
reproducible in CLI. javac API is harder to debug (e.g. I didn't manage
to explicitly pass `-target 17` flag because javac API was failing with
"Unrecognized option : -target 61", although this flag works in CLI)

GitOrigin-RevId: ae69decbd589e0bc37fe7a4b2bfaf639fd24cba7